Improve responsive design for gift cards
hps/heartland-woocommerce-plugin pull request #208
Opened 2023-08-14 15:38 UTC by tflight

This PR does not incorporate changes in https://github.com/hps/heartland-woocommerce-plugin/pull/207

In smaller browser widths, say 320x568 of the iPhone SE, the gift card number field would overflow the page and is difficult to see while entering. This changes the layout of the gift card number and PIN fields to use the responsive layout provided in WooCommerce just like the credit card number and expiration date fields above use.

Additionally, this PR adds labels to the gift card number and PIN fields to improve accessibility and provide a more consistent visual match with the credit card fields.

2023-09-21 15:46 UTC, MSmedal requested changes
These changes improve the layout for smaller viewports, but may be a step backwards when a larger viewport is in use (and the two input fields become inline). Can you modify these changes to better account for larger screens?

2023-09-21 17:54 UTC, tflight commented
They layout should match the responsiveness of the expiration date and security code fields. (On wider displays they take up 50% of the width of the page container, stack on small displays.) Since this commit doesn't include a version number change to bust the cache of the CSS file can you check if your browser was referencing a cached version of the CSS file?

2023-09-21 17:56 UTC, tflight commented
And thank you, @MSmedal, for taking a look at these. I very much appreciate it! 👍🏻

2023-09-23 14:58 UTC, MSmedal commented
> They layout should match the responsiveness of the expiration date and security code fields. (On wider displays they take up 50% of the width of the page container, stack on small displays.) Since this commit doesn't include a version number change to bust the cache of the CSS file can you check if your browser was referencing a cached version of the CSS file?

The layout for the gift card number and gift card field inputs shouldn't match the credit card expiration date and credit card security code fields as much as they should match the credit card number and credit card security code fields (since the input lengths most closely match them). If you could have a look at this design with a viewport of 769px to about 900px wide I think you'll see what I mean.

2023-09-25 12:45 UTC, tflight commented
Below are screenshots at widths of 320, ~780, and 1920 for the WordPress default Twenty Twenty-Three theme, what I'd consider the WooCommerce "default" theme Storefront, and my theme. Given how some of these themes are putting the payment fields in a narrow column, [container queries](https://caniuse.com/css-container-query-units) might be considered over viewport/media queries. There are some dashboard/toolbar artifacts in these I missed taking out but were not the cause of some of the super squished elements and overflowing elements.

![twentythree-1920](https://github.com/hps/heartland-woocommerce-plugin/assets/4959691/194604c4-722c-4c04-9810-9c488613495c)
![twentythree-783](https://github.com/hps/heartland-woocommerce-plugin/assets/4959691/403034dc-7272-4fed-ae72-8c00c1c04297)
![twentythree-320](https://github.com/hps/heartland-woocommerce-plugin/assets/4959691/c1f094ea-2f9b-4a6d-b161-6e4d72dcc438)
![storefront-1920](https://github.com/hps/heartland-woocommerce-plugin/assets/4959691/a68498f6-ae87-4824-87d6-6891821f2b68)
![storefront-783](https://github.com/hps/heartland-woocommerce-plugin/assets/4959691/cca712d0-8793-454a-9178-9a5d0d2a31ea)
![storefront-320](https://github.com/hps/heartland-woocommerce-plugin/assets/4959691/89672972-bbee-462b-8087-ca6407843d15)
![cc-1920](https://github.com/hps/heartland-woocommerce-plugin/assets/4959691/82d2a49a-0bb0-48e8-9494-8da2daba0c99)
![cc-785](https://github.com/hps/heartland-woocommerce-plugin/assets/4959691/3ed50c1f-6bdd-41e1-bc00-984746a6cb52)
![cc-320](https://github.com/hps/heartland-woocommerce-plugin/assets/4959691/8692abf1-8d02-4202-9a2f-63bd1c43d36f)

2024-11-22 19:41 UTC, closed without merging